### ISSUE TITLE
`IsADirectoryError` when building image

### ISSUE THREAD

**Issue by multimeric** [prehensilecode/alphafold_singularity#13]
Hi. When I try to build the image from the `.def` file, the commands succeed until the following:
```
+ bash /tmp/Miniconda3-py37_4.12.0-Linux-x86_64.sh -b -p /opt/conda
PREFIX=/opt/conda
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 243, in _process_worker
  File "concurrent/futures/process.py", line 202, in _process_chunk
  File "concurrent/futures/process.py", line 202, in <listcomp>
  File "site-packages/conda_package_handling/api.py", line 58, in extract
  File "site-packages/conda_package_handling/conda_fmt.py", line 59, in extract
  File "site-packages/conda_package_handling/conda_fmt.py", line 40, in _extract_component
  File "zipfile.py", line 1616, in extract
  File "zipfile.py", line 1687, in _extract_member
IsADirectoryError: [Errno 21] Is a directory: '/opt/conda/pkgs/pysocks-1.7.1-py37_1u7jrvhn3/pkg-pysocks-1.7.1-py37_1.tar.zst'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 608, in result_iterator
  File "concurrent/futures/_base.py", line 438, in result
  File "concurrent/futures/_base.py", line 390, in __get_result
IsADirectoryError: [Errno 21] Is a directory: '/opt/conda/pkgs/pysocks-1.7.1-py37_1u7jrvhn3/pkg-pysocks-1.7.1-py37_1.tar.zst'
[21356] Failed to execute script entry_point
```

**Comment by prehensilecode** [comment]
How much space do you have in your `/tmp` and/or build directory? The build process requires up to 15 GB.

Also, what version of Singularity or Apptainer are you using to build?
